//! Generates the tables that bake browser assets and translations into the binary.
//!
//! Everything is found by walking directories at build time, so adding a file — an
//! engine module, a widget module, a dialogue, or a whole new language — never means
//! editing source:
//!
//!   web/autoplay/engine/*.js     autoplay engine modules (excluding *.test.js)
//!   web/cheat/widget/*.js        cheat widget modules (excluding *.test.js)
//!   locale/i18n.<lang>.json      one UI translation per language
//!   locale/dialogs/<lang>/*.ink  that language's dialogue
//!   locale/fonts/*.woff2         the fonts the language catalogue refers to

use std::{env, fs, path::Path};

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();

    // Concatenation order is the dependency order: the entry file reads these modules
    // off a window namespace, so they have to run first. Sorting keeps that stable.
    gen_files(
        Path::new("web/autoplay/engine"),
        "js",
        |stem| !stem.ends_with(".test"),
        "ENGINE_MODULES",
        "(module name, source). Injected before engine.js, in this order",
        &Path::new(&out_dir).join("engine_modules.rs"),
    );
    gen_files(
        Path::new("web/cheat/widget"),
        "js",
        |stem| !stem.ends_with(".test"),
        "WIDGET_MODULES",
        "(module name, source). Injected before widget.js, in this order",
        &Path::new(&out_dir).join("widget_modules.rs"),
    );

    gen_locales(&Path::new(&out_dir).join("locales.rs"));
}

/// Every language's assets, gathered from the layout all of them share.
fn gen_locales(dest: &Path) {
    let locale = Path::new("locale");
    println!("cargo:rerun-if-changed=locale");

    let mut langs: Vec<String> = Vec::new();
    if let Ok(rd) = fs::read_dir(locale) {
        for e in rd.flatten() {
            let name = e.file_name().to_string_lossy().into_owned();
            if let Some(rest) = name.strip_prefix("i18n.") {
                if let Some(lang) = rest.strip_suffix(".json") {
                    println!("cargo:rerun-if-changed=locale/{name}");
                    langs.push(lang.to_owned());
                }
            }
        }
    }
    langs.sort();

    let mut out = String::from(
        "/// One dialogue file: its id and its text.\n\
         pub type Dialogue = (&'static str, &'static str);\n\
         \n\
         /// One language: its code, its UI table as JSON, and its dialogue.\n\
         pub type Locale = (&'static str, &'static str, &'static [Dialogue]);\n\
         \n\
         /// Every language in this binary. Generated by build.rs.\n\
         pub static LOCALES: &[Locale] = &[\n",
    );
    let mut tables = String::new();
    for lang in &langs {
        let dialogs_dir = locale.join("dialogs").join(lang);
        println!("cargo:rerun-if-changed={}", dialogs_dir.display());
        let ident = lang.replace('-', "_").to_uppercase();
        tables.push_str(&format!(
            "static DIALOGS_{ident}: &[(&str, &str)] = &[\n{}];\n",
            dialogue_entries(&dialogs_dir)
        ));
        out.push_str(&format!(
            "    ({lang:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/locale/i18n.{lang}.json\")), DIALOGS_{ident}),\n"
        ));
    }
    out.push_str("];\n\n");
    out.push_str(&tables);

    // The font files the catalogue refers to, so they can be served by name.
    let fonts_dir = locale.join("fonts");
    println!("cargo:rerun-if-changed={}", fonts_dir.display());
    out.push_str(
        "\n/// (file name, bytes) for every bundled font. Generated by build.rs.\n\
         pub static FONTS: &[(&str, &[u8])] = &[\n",
    );
    let mut fonts: Vec<String> = Vec::new();
    if let Ok(rd) = fs::read_dir(&fonts_dir) {
        for e in rd.flatten() {
            let p = e.path();
            if p.extension().and_then(|s| s.to_str()) == Some("woff2") {
                fonts.push(p.file_name().unwrap().to_string_lossy().into_owned());
            }
        }
    }
    fonts.sort();
    for f in &fonts {
        out.push_str(&format!(
            "    ({f:?}, include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/locale/fonts/{f}\"))),\n"
        ));
    }
    out.push_str("];\n");

    // The flag PNGs. Every language the settings screen offers needs its own, not
    // only the one being applied — the list shows all of them at once, and a flag
    // whose file never arrives is drawn as a broken image.
    let flags_dir = locale.join("flags");
    println!("cargo:rerun-if-changed={}", flags_dir.display());
    out.push_str(
        "\n/// (file name, bytes) for every bundled flag. Generated by build.rs.\n\
         pub static FLAGS: &[(&str, &[u8])] = &[\n",
    );
    let mut flags: Vec<String> = Vec::new();
    if let Ok(rd) = fs::read_dir(&flags_dir) {
        for e in rd.flatten() {
            let p = e.path();
            if p.extension().and_then(|s| s.to_str()) == Some("png") {
                flags.push(p.file_name().unwrap().to_string_lossy().into_owned());
            }
        }
    }
    flags.sort();
    for f in &flags {
        out.push_str(&format!(
            "    ({f:?}, include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/locale/flags/{f}\"))),\n"
        ));
    }
    out.push_str("];\n");

    fs::write(dest, out).unwrap_or_else(|e| panic!("could not write {}: {e}", dest.display()));
}

fn dialogue_entries(dir: &Path) -> String {
    let mut entries: Vec<(String, String)> = Vec::new();
    if let Ok(rd) = fs::read_dir(dir) {
        for e in rd.flatten() {
            let p = e.path();
            if p.extension().and_then(|s| s.to_str()) != Some("ink") {
                continue;
            }
            let Some(stem) = p.file_stem().and_then(|s| s.to_str()) else {
                continue;
            };
            println!("cargo:rerun-if-changed={}", p.display());
            entries.push((stem.to_owned(), p.to_string_lossy().replace('\\', "/")));
        }
    }
    entries.sort();
    let mut out = String::new();
    for (id, path) in &entries {
        out.push_str(&format!(
            "    ({id:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{path}\"))),\n"
        ));
    }
    out
}

fn gen_files(
    dir: &Path,
    ext: &str,
    keep: impl Fn(&str) -> bool,
    name: &str,
    doc: &str,
    dest: &Path,
) {
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut entries: Vec<(String, String)> = Vec::new();
    if let Ok(rd) = fs::read_dir(dir) {
        for e in rd.flatten() {
            let p = e.path();
            if p.extension().and_then(|s| s.to_str()) != Some(ext) {
                continue;
            }
            let Some(stem) = p.file_stem().and_then(|s| s.to_str()) else {
                continue;
            };
            if !keep(stem) {
                continue;
            }
            println!("cargo:rerun-if-changed={}", p.display());
            entries.push((stem.to_owned(), p.to_string_lossy().replace('\\', "/")));
        }
    }
    entries.sort();

    let mut out =
        format!("/// {doc}. Generated by build.rs.\npub static {name}: &[(&str, &str)] = &[\n");
    for (id, path) in &entries {
        out.push_str(&format!(
            "    ({id:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{path}\"))),\n"
        ));
    }
    out.push_str("];\n");

    fs::write(dest, out).unwrap_or_else(|e| panic!("could not write {}: {e}", dest.display()));
}
