//! What ships inside the binary. Nothing here touches the file system.
//!
//! The browser-side JS and every translation are baked into the executable so the
//! whole mod is one file. Anything extracted from the game — the English source
//! strings, the upgrade tree — is deliberately absent; that is read from the bundle
//! at runtime.

use crate::language::{Catalogue, Font};
use std::collections::HashMap;

/// Scripts that run in the browser, injected before the document loads.
pub const CHEAT_WIDGET: &str = include_str!("../web/cheat/widget.js");
pub const AUTOPLAY_ENGINE: &str = include_str!("../web/autoplay/engine.js");
pub const AUTOPLAY_PANEL: &str = include_str!("../web/autoplay/panel.js");

/// Which languages exist, how to recognise them, and what to render them with.
const LANGUAGES: &str = include_str!("../locale/languages.json");

// Generated by build.rs, which walks web/autoplay/engine/*.js. Order matters: these
// register themselves on window.__bd_mod, and engine.js reads them from there.
include!(concat!(env!("OUT_DIR"), "/engine_modules.rs"));

// The same, for web/cheat/widget/*.js and window.__bd_cheat_mod.
include!(concat!(env!("OUT_DIR"), "/widget_modules.rs"));

// Every translation and every font, from locale/. Generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/locales.rs"));

pub fn catalogue() -> Result<Catalogue, String> {
    serde_json::from_str(LANGUAGES)
        .map_err(|e| format!("could not read locale/languages.json: {e}"))
}

/// The language codes this binary can actually apply.
pub fn available() -> Vec<String> {
    LOCALES
        .iter()
        .map(|(code, _, _)| (*code).to_owned())
        .collect()
}

/// One language's UI table.
pub fn tables(lang: &str) -> Result<serde_json::Value, String> {
    let (_, json, _) = LOCALES
        .iter()
        .find(|(code, _, _)| *code == lang)
        .ok_or_else(|| format!("no {lang} translation is bundled"))?;
    serde_json::from_str(json).map_err(|e| format!("could not read the {lang} translation: {e}"))
}

/// One language's dialogue, keyed by file name.
pub fn dialogs(lang: &str) -> HashMap<&'static str, &'static str> {
    let mut m = HashMap::new();
    if let Some((_, _, list)) = LOCALES.iter().find(|(code, _, _)| *code == lang) {
        for (name, body) in *list {
            m.insert(*name, *body);
        }
    }
    m
}

/// The bytes of a bundled font file, by name.
pub fn font_bytes(file: &str) -> Option<&'static [u8]> {
    FONTS
        .iter()
        .find(|(name, _)| *name == file)
        .map(|(_, bytes)| *bytes)
}

/// The flag a request is asking for.
///
/// Every language in the settings list needs its flag served, not just the one being
/// applied: the list shows all of them at once, and a language whose PNG never
/// arrives is drawn as a broken image. The game's own five keep their own files, so
/// only names we put into the flag map are answered here.
pub fn flag_for(url: &str, carried: &[crate::patch::Carried]) -> Option<&'static [u8]> {
    if !url.contains("/flags/") {
        return None;
    }
    let name = url.rsplit('/').next()?.split(['?', '#']).next()?;
    if !carried.iter().any(|c| c.flag_file == name) {
        return None;
    }
    FLAGS
        .iter()
        .find(|(f, _)| *f == name)
        .map(|(_, bytes)| *bytes)
}

/// The font a request is asking for, matched against the URLs this language plants
/// in the CSS. A URL we did not plant is not ours to answer.
pub fn font_for<'a>(url: &str, fonts: &'a [Font]) -> Option<(&'a Font, &'static [u8])> {
    fonts
        .iter()
        .find(|f| url.contains(&f.url))
        .and_then(|f| font_bytes(&f.file).map(|b| (f, b)))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_catalogue_parses() {
        let cat = catalogue().unwrap();
        assert!(!cat.languages.is_empty());
    }

    #[test]
    fn every_language_the_settings_screen_offers_has_its_flag_embedded() {
        // The flag map goes into the bundle for every carried language, so every one
        // of those files has to be answerable. Missing one shows as a broken image in
        // the settings screen, which is what happened when the flags were shipped in
        // the repository but never embedded in the binary.
        let cat = catalogue().unwrap();
        for lang in available() {
            let def = cat.languages.get(&lang).expect("catalogue entry");
            assert!(!def.flag_file.is_empty(), "{lang}: no flagFile");
            assert!(
                FLAGS.iter().any(|(f, _)| *f == def.flag_file),
                "{lang}: {} is not embedded",
                def.flag_file
            );
        }
    }

    #[test]
    fn a_flag_is_served_only_for_a_language_actually_offered() {
        let cat = catalogue().unwrap();
        let carried = crate::patch::carry(&cat, "ko");
        assert!(flag_for("gemshell://x/flags/kr.png", &carried).is_some());
        // A flag the game ships itself, and one no language asked for.
        assert!(flag_for("gemshell://x/flags/us.png", &carried).is_none());
        assert!(flag_for("gemshell://x/flags/kr.png", &[]).is_none());
        // A query string must not defeat the name match.
        assert!(flag_for("gemshell://x/flags/kr.png?v=2", &carried).is_some());
        // Not a flag request at all.
        assert!(flag_for("gemshell://x/assets/kr.png", &carried).is_none());
    }

    #[test]
    fn every_bundled_language_is_in_the_catalogue() {
        // The catalogue is the roadmap and may list languages nobody has translated
        // yet — that is the point of it. The reverse must not happen: a bundled
        // translation with no catalogue entry has no flag, no font and no locale
        // prefixes, so it could never be selected.
        let cat = catalogue().unwrap();
        for lang in available() {
            assert!(
                cat.languages.contains_key(&lang),
                "{lang}: bundled but not in locale/languages.json"
            );
        }
    }

    #[test]
    fn every_bundled_language_has_a_usable_table() {
        for lang in available() {
            let v = tables(&lang).unwrap_or_else(|e| panic!("{lang}: {e}"));
            assert!(v.get("upgrades").is_some(), "{lang}: no upgrades namespace");
        }
    }

    #[test]
    fn a_language_that_ships_dialogue_ships_all_of_it() {
        // Dialogue is a separate deliverable from the UI table, so having none is
        // allowed. Having some but not all is not: the game would show a mix of
        // languages inside one conversation.
        let full = dialogs("ko").len();
        assert!(full > 0, "ko is the reference and must have dialogue");
        for lang in available() {
            let n = dialogs(&lang).len();
            assert!(
                n == 0 || n == full,
                "{lang}: {n} dialogue files, but the reference has {full}"
            );
        }
    }

    #[test]
    fn every_font_a_language_names_is_bundled() {
        let cat = catalogue().unwrap();
        for (lang, def) in &cat.languages {
            for f in &def.fonts {
                assert!(
                    font_bytes(&f.file).is_some_and(|b| b.len() > 1000),
                    "{lang}: {} is named but not bundled",
                    f.file
                );
            }
        }
    }

    #[test]
    fn a_font_is_matched_by_the_url_we_planted() {
        let cat = catalogue().unwrap();
        let ko = &cat.languages["ko"];
        // From the catalogue, not written out here: each language has its own URL now,
        // and a test that hardcodes one is a test that fails the day that changes for a
        // reason it was never about.
        let url = &ko.fonts[0].url;
        assert!(font_for(&format!("gemshell://x/{url}"), &ko.fonts).is_some());
        assert!(font_for("gemshell://x/fonts/other.woff2", &ko.fonts).is_none());
        assert!(font_for(&format!("gemshell://x/{url}"), &[]).is_none());
    }

    #[test]
    fn the_widget_modules_are_embedded() {
        assert!(!WIDGET_MODULES.is_empty(), "no widget module was embedded");
        for (name, body) in WIDGET_MODULES {
            assert!(!name.ends_with(".test"), "{name}: tests must not ship");
            assert!(
                body.contains("__bd_cheat_mod"),
                "{name}: does not register itself"
            );
        }
    }

    #[test]
    fn the_engine_modules_are_embedded() {
        // engine.js reads these off window.__bd_mod. Ship none and autoplay dies
        // silently in the renderer, where nothing reaches the launcher log.
        assert!(!ENGINE_MODULES.is_empty(), "no engine module was embedded");
        for (name, body) in ENGINE_MODULES {
            assert!(!name.ends_with(".test"), "{name}: tests must not ship");
            assert!(
                body.contains("__bd_mod"),
                "{name}: does not register itself"
            );
        }
    }
}
